variables:
  MYSQL_USER: dev
  MYSQL_PASSWORD: dev
  MYSQL_DATABASE: dev
  MYSQL_ROOT_PASSWORD: dev

test:
  image: pretzlaw/php:7.1-apache
  services:
    - name: mariadb
      alias: db

  before_script:
    - cp .env.dist .env

  script:
    - ls