variables:
  MYSQL_USER: dev
  MYSQL_PASSWORD: dev
  MYSQL_DATABASE: dev
  MYSQL_ROOT_PASSWORD: dev

.test: &test
  image: pretzlaw/php:7.1-apache
  services:
    - name: mariadb
      alias: db

  variables:
    WP_VERSION: "latest"

  before_script:
    - cp .env.dist .env
    - composer install

  script:
    - vendor/bin/wp --allow-root core download --version=$WP_VERSION
    - ls

wp:
  extends: ".test"

wp50:
  extends: ".test"
  variables:
    WP_VERSION: "5.0"