variables:
  MYSQL_USER: dev
  MYSQL_PASSWORD: dev
  MYSQL_DATABASE: dev


test:
  image: pretzlaw/php:7.1-apache
  services:
    - name: mariadb
      alias: db
  script:
    - ls
    - env
    - ping -c1 db