version: '3'

services:
  # additionally use fpm for better performance
  php71:
    image: pretzlaw/php:7.1-fpm
    volumes:
      - ".:/var/www"
      - "$COMPOSER_LOCAL:/var/composer"
    env_file: [ .env ]
    networks:
      default:
        ipv4_address: 10.210.9.10

  db:
    image: mysql:5.6
    volumes:
      - ".docker/db:/var/lib/mysql"
    environment:
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
      MYSQL_DATABASE: dev
      MYSQL_ROOT_PASSWORD: dev
    networks:
      default:
        ipv4_address: 10.210.9.11

networks:
  default:
    ipam:
      config:
        - subnet: 10.210.9.0/24
